import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Date from '../component/date';
import { getSortedJobsData } from '../lib/jobs';
import Link from 'next/link';


export async function getStaticProps() {
  const allJobsData = getSortedJobsData();
  return {
    props: {
      allJobsData,
    },
  };
}

export default function Home({allJobsData}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Application Tracking Application Thing: ATAT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          AT-AT
        </h1>

        <p className={styles.description}>
          Get started by logging in register/login link goes here
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Closed Apps &rarr;</h2>
            <p>A historical record of rejections, its not you it us, and you are perfect but...</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Active Apps &rarr;</h2>
            <p>Currently applied or in process or as we call them pre-failures</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Prospects &rarr;</h2>
            <p>Potential application targets or future failures go here, scout away</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Data Tracking &rarr;</h2>
            <p>
              Pretty chartJS tracking of all your failures goes here, for all eternity
            </p>
          </a>
        </div>
        <h2>Projects</h2>
        <div >
          {allJobsData.map(({ id, date, title, img }) => (
          <Link href={`/jobs/${id}`} key={id}>
            <div >
              
                {title}
              
              <Image
                priority
                src={img}
                height={144}
                width={200}
                alt=""
               
              />
              <small>
                <Date dateString={date} />
              </small>
            </div>
          </Link>
        
          ))}
          </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
